[build]
command = "bun install --no-cache && bun run build"
publish = ".next"
environment = { NEXT_PRIVATE_UNSTABLE_NO_EDGE = "1" }

[[plugins]]
package = "@netlify/plugin-nextjs"
  [plugins.inputs]
  disableEdge = true
